#

pluginName = Documentation Schema Model Edit Support
providerName = Vasily Fedorov

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Named_type = Named
_UI_Library_type = Library
_UI_Rules_type = Rules
_UI_DocumentationLanguage_type = Documentation Language
_UI_DocumentationEngine_type = Documentation Engine
_UI_Organization_type = Organization
_UI_Book_type = Book
_UI_Parameter_type = Parameter
_UI_Rule_type = Rule
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Named_name_feature = Name
_UI_Library_rules_feature = Rules
_UI_Rules_rules_feature = Rules
_UI_Book_parameters_feature = Parameters
_UI_Book_language_feature = Language
_UI_Book_engine_feature = Engine
_UI_Book_organization_feature = Organization
_UI_Parameter_initial_feature = Initial
_UI_Rule_pattern_feature = Pattern
_UI_Rule_result_feature = Result
_UI_Rule_priority_feature = Priority
_UI_Unknown_feature = Unspecified

