/**
 */
package ru.mkn.sovesti.screbok.mlm.edit.providers;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IItemStyledLabelProvider;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ru.mkn.sovesti.screbok.mlm.model.util.MlmAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MlmItemProviderAdapterFactory extends MlmAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MlmItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(IItemStyledLabelProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Site} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SiteItemProvider siteItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Site}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSiteAdapter() {
		if (siteItemProvider == null) {
			siteItemProvider = new SiteItemProvider(this);
		}

		return siteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.SitePage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SitePageItemProvider sitePageItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.SitePage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSitePageAdapter() {
		if (sitePageItemProvider == null) {
			sitePageItemProvider = new SitePageItemProvider(this);
		}

		return sitePageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.SiteMedia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SiteMediaItemProvider siteMediaItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.SiteMedia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSiteMediaAdapter() {
		if (siteMediaItemProvider == null) {
			siteMediaItemProvider = new SiteMediaItemProvider(this);
		}

		return siteMediaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Placeholder} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlaceholderItemProvider placeholderItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Placeholder}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlaceholderAdapter() {
		if (placeholderItemProvider == null) {
			placeholderItemProvider = new PlaceholderItemProvider(this);
		}

		return placeholderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.WrappingNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WrappingNodeItemProvider wrappingNodeItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.WrappingNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWrappingNodeAdapter() {
		if (wrappingNodeItemProvider == null) {
			wrappingNodeItemProvider = new WrappingNodeItemProvider(this);
		}

		return wrappingNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.ImaginaryNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImaginaryNodeItemProvider imaginaryNodeItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.ImaginaryNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImaginaryNodeAdapter() {
		if (imaginaryNodeItemProvider == null) {
			imaginaryNodeItemProvider = new ImaginaryNodeItemProvider(this);
		}

		return imaginaryNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.NodeAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeAttributeItemProvider nodeAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.NodeAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeAttributeAdapter() {
		if (nodeAttributeItemProvider == null) {
			nodeAttributeItemProvider = new NodeAttributeItemProvider(this);
		}

		return nodeAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Wildcard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WildcardItemProvider wildcardItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Wildcard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWildcardAdapter() {
		if (wildcardItemProvider == null) {
			wildcardItemProvider = new WildcardItemProvider(this);
		}

		return wildcardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Section} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SectionItemProvider sectionItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Section}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSectionAdapter() {
		if (sectionItemProvider == null) {
			sectionItemProvider = new SectionItemProvider(this);
		}

		return sectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Anchor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnchorItemProvider anchorItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Anchor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnchorAdapter() {
		if (anchorItemProvider == null) {
			anchorItemProvider = new AnchorItemProvider(this);
		}

		return anchorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.MarkupList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MarkupListItemProvider markupListItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.MarkupList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMarkupListAdapter() {
		if (markupListItemProvider == null) {
			markupListItemProvider = new MarkupListItemProvider(this);
		}

		return markupListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.RawText} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RawTextItemProvider rawTextItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.RawText}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRawTextAdapter() {
		if (rawTextItemProvider == null) {
			rawTextItemProvider = new RawTextItemProvider(this);
		}

		return rawTextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.CodeListing} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeListingItemProvider codeListingItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.CodeListing}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeListingAdapter() {
		if (codeListingItemProvider == null) {
			codeListingItemProvider = new CodeListingItemProvider(this);
		}

		return codeListingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Reference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceItemProvider referenceItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Reference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceAdapter() {
		if (referenceItemProvider == null) {
			referenceItemProvider = new ReferenceItemProvider(this);
		}

		return referenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Image} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageItemProvider imageItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Image}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAdapter() {
		if (imageItemProvider == null) {
			imageItemProvider = new ImageItemProvider(this);
		}

		return imageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.Emphasized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmphasizedItemProvider emphasizedItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.Emphasized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmphasizedAdapter() {
		if (emphasizedItemProvider == null) {
			emphasizedItemProvider = new EmphasizedItemProvider(this);
		}

		return emphasizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.mkn.sovesti.screbok.mlm.model.api.LineBreak} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineBreakItemProvider lineBreakItemProvider;

	/**
	 * This creates an adapter for a {@link ru.mkn.sovesti.screbok.mlm.model.api.LineBreak}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineBreakAdapter() {
		if (lineBreakItemProvider == null) {
			lineBreakItemProvider = new LineBreakItemProvider(this);
		}

		return lineBreakItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (siteItemProvider != null) siteItemProvider.dispose();
		if (sitePageItemProvider != null) sitePageItemProvider.dispose();
		if (siteMediaItemProvider != null) siteMediaItemProvider.dispose();
		if (nodeAttributeItemProvider != null) nodeAttributeItemProvider.dispose();
		if (wildcardItemProvider != null) wildcardItemProvider.dispose();
		if (placeholderItemProvider != null) placeholderItemProvider.dispose();
		if (wrappingNodeItemProvider != null) wrappingNodeItemProvider.dispose();
		if (imaginaryNodeItemProvider != null) imaginaryNodeItemProvider.dispose();
		if (sectionItemProvider != null) sectionItemProvider.dispose();
		if (anchorItemProvider != null) anchorItemProvider.dispose();
		if (markupListItemProvider != null) markupListItemProvider.dispose();
		if (rawTextItemProvider != null) rawTextItemProvider.dispose();
		if (codeListingItemProvider != null) codeListingItemProvider.dispose();
		if (referenceItemProvider != null) referenceItemProvider.dispose();
		if (imageItemProvider != null) imageItemProvider.dispose();
		if (emphasizedItemProvider != null) emphasizedItemProvider.dispose();
		if (lineBreakItemProvider != null) lineBreakItemProvider.dispose();
	}

}
