#

pluginName = Markup Language Model Edit Support
providerName = Vasily Fedorov

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Located_type = Located
_UI_Site_type = Site
_UI_SiteResource_type = Site Resource
_UI_SitePage_type = Site Page
_UI_SiteMedia_type = Site Media
_UI_MarkupNode_type = Markup Node
_UI_NodeAttribute_type = Node Attribute
_UI_MultiPlaceholder_type = Multi Placeholder
_UI_Placeholder_type = Placeholder
_UI_WrappingNode_type = Node
_UI_ImaginaryNode_type = Imaginary Node
_UI_Section_type = Section
_UI_MarkupList_type = Markup List
_UI_RawText_type = Raw Text
_UI_CodeListing_type = Code Listing
_UI_Reference_type = Reference
_UI_Emphasized_type = Emphasized
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Located_uri_feature = Uri
_UI_Site_resources_feature = Resources
_UI_SiteResource_site_feature = Site
_UI_SitePage_elements_feature = Elements
_UI_MarkupNode_language_feature = Language
_UI_MarkupNode_name_feature = Name
_UI_MarkupNode_attributes_feature = Attributes
_UI_RawText_text_feature = Text
_UI_NodeAttribute_name_feature = Name
_UI_NodeAttribute_value_feature = Value
_UI_MultiPlaceholder_key_feature = Key
_UI_Placeholder_key_feature = Key
_UI_Placeholder_width_feature = Width
_UI_WrappingNode_children_feature = Children
_UI_ImaginaryNode_key_feature = Key
_UI_ImaginaryNode_origin_feature = Origin
_UI_Section_level_feature = Level
_UI_Section_title_feature = Title
_UI_Section_children_feature = Children
_UI_MarkupList_type_feature = Type
_UI_MarkupList_items_feature = Items
_UI_CodeListing_content_feature = Content
_UI_Reference_title_feature = Title
_UI_Reference_link_feature = Link
_UI_Reference_referenced_feature = Referenced
_UI_Emphasized_type_feature = Type
_UI_Emphasized_parts_feature = Parts
_UI_Unknown_feature = Unspecified

_UI_ListType_BULLETED_literal = BULLETED
_UI_ListType_NUMBERED_literal = NUMBERED
_UI_EmphasisType_ITALIC_literal = ITALIC
_UI_EmphasisType_BOLD_literal = BOLD
_UI_SitePage_name_feature = Name
_UI_SitePage_root_feature = Root
_UI_Placeholder_width_feature = Width
_UI_Wildcard_type = Wildcard
_UI_Wildcard_key_feature = Key
_UI_Wildcard_repeated_feature = Repeated
_UI_LineBreak_type = Line Break
_UI_Image_type = Image
_UI_Image_link_feature = Link
_UI_Reference_content_feature = Content
_UI_Anchor_type = Anchor
_UI_Section_anchor_feature = Anchor
_UI_WrappingNode_transient_feature = Transient
