#

pluginName = Screbok Launch Model Edit Support
providerName = Vasily Fedorov

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Launch_type = Launch
_UI_Action_type = Action
_UI_Scrap_type = Scrap
_UI_Convert_type = Convert
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Launch_actions_feature = Actions
_UI_Action_output_feature = Output
_UI_Scrap_pages_feature = Pages
_UI_Convert_book_feature = Book
_UI_Convert_pages_feature = Pages
_UI_Convert_format_feature = Format
_UI_Unknown_feature = Unspecified

_UI_Format_MARKDOWN_literal = MARKDOWN
