<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="slm" nsURI="http://www.sovesti.ru/screbok/slm" nsPrefix="slm">
  <eClassifiers xsi:type="ecore:EClass" name="Launch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="../../ru.mkn.sovesti.screbok.dsm.model/model/dsm.ecore#//Named">
    <eOperations name="run" eExceptions="#//CoreException">
      <eParameters name="context" eType="#//LaunchContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scrap" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="ecore:EClass ../../ru.mkn.sovesti.screbok.mlm.model/model/mlm.ecore#//SitePage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Convert" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="ecore:EClass ../../ru.mkn.sovesti.screbok.dsm.model/model/dsm.ecore#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="ecore:EClass ../../ru.mkn.sovesti.screbok.mlm.model/model/mlm.ecore#//SitePage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//Format"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Format">
    <eLiterals name="MARKDOWN" literal="MARKDOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LaunchContext" instanceClassName="ru.mkn.sovesti.screbok.slm.model.LaunchContext"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CoreException" instanceClassName="org.eclipse.core.runtime.CoreException"/>
</ecore:EPackage>
