name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.13
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ru.mkn.sovesti.screbok
          path: ru.mkn.sovesti.screbok/products/ru.mkn.sovesti.screbok.product/target/ru.mkn.sovesti.screbok*.zip
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ru.mkn.sovesti.screbok.cli
          path:  /home/runner/work/screbok/screbok/products/ru.mkn.sovesti.screbok.product/target/ru.mkn.sovesti.screbok.product-*.zip

  test:
    runs-on: [ubuntu-24.04]
    needs: [build]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.13
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots clean verify